import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const robotoFont = Roboto({
  variable: "--font-Roboto",
  style: ["italic", "normal"],
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"]
})

export const metadata: Metadata = {
  title: "Coin Visualizer",
  description: "A simple Coin Price Visualizer generated By Next and Developed by Ferreira",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${robotoFont.variable} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
