import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const interFont = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
  weight: ["100", "400", "600", "700", "900"]
})

export const metadata: Metadata = {
  title: "Coin Visualizer",
  description: "A simple Coin Price Visualizer generated By Next and Developed by Ferreira",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${interFont.variable} antialiased bg-gradient-to-b from-blue-950 to-neutral-950`}
      >
        {children}
      </body>
    </html>
  );
}
